### ISSUE TITLE
Game only updates in fullscreen mode when I open steam overlay

### ISSUE THREAD

**Issue by ElwoodHogan** [sbritorodr/df-sdl12-compat#4]
https://youtu.be/iyB1RIuCtRU

**Comment by ElwoodHogan** [comment]
Also, as you can see in the video, there are weird magenta bars on the bottom and right side of the screen.

**Comment by sbritorodr** [comment]
Hello @ElwoodHogan . Unfortunately I can't help you since this workaround will be completely useless by the end of this month, as devs have said on their blog page. This repository is a mirror of the direct libsdl2-compat and I have no access with the main source code of the game neither understand completely SDL2 to fix your issue.

For now on i think it's better to just keep playing with old SDL and leave this workaround appart.
